# Generated by Django 3.2.7 on 2021-10-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogify', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Clock the link above to read the blog post...', max_length=255),
        ),
    ]
