# Generated by Django 3.2.7 on 2021-10-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogify', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
